# Generated by Django 3.1.1 on 2020-09-22 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='User',
            new_name='user',
        ),
    ]
